### ISSUE TITLE
KeyError: b'CInf' for a BEAM file

### ISSUE THREAD

**Issue by marxin** [matwey/pybeam#14]
The following fails:

```
BeamFile('Elixir.IEx.Introspection.beam').compileinfo['source']

KeyError                                  Traceback (most recent call last)
<ipython-input-3-7cf8d4bc6f05> in <module>
----> 1 _2.compileinfo['source']

/usr/lib/python3.8/site-packages/pybeam/beam_file.py in compileinfo(self)
     56         @property
     57         def compileinfo(self):
---> 58                 cinf = self.selectChunkByName(b"CInf")
     59                 return dict(cinf.payload)
     60 

/usr/lib/python3.8/site-packages/pybeam/beam_file.py in selectChunkByName(self, name)
     33                         if c.chunk_name == name:
     34                                 return c
---> 35                 raise KeyError(name)
     36 
     37         @property

KeyError: b'CInf'
```

[Elixir.IEx.Introspection.beam.txt](https://github.com/matwey/pybeam/files/5477601/Elixir.IEx.Introspection.beam.txt)

**Comment by matwey** [comment]
Hi,

Thank you for the report. I'll look into it, though it'll take some time.

I've never tried to open Elixir BEAMs. Are you sure that compile info should be present there? Normally, you can disable it even for Erlang: https://erlang.org/doc/man/compile.html (see `compile_info`).

**Comment by matwey** [comment]
Well, I've found that there is `FunT` chunk in a file, which currently cannot be parsed. And file parsing was silently broken here. I don't like such behavior.

The plan is:
* ensure that the parsing is failing at unknown chunk types
* support `FunT` to be able to parse the file completely
* make `compileinfo` property (and others) return `None` if chunk cannot be found.

**Comment by marxin** [comment]
> I've never tried to open Elixir BEAMs. Are you sure that compile info should be present there? Normally, you can disable it even for Erlang: https://erlang.org/doc/man/compile.html (see `compile_info`).



> Thank you for the report. I'll look into it, though it'll take some time.

Thank you!

> 
> I've never tried to open Elixir BEAMs. Are you sure that compile info should be present there? Normally, you can disable it even for Erlang: https://erlang.org/doc/man/compile.html (see `compile_info`).

I must confirm I'm not much familiar with BEAMs. The elixir package is btw. built here:
https://build.opensuse.org/package/show/devel:languages:erlang/elixir

**Comment by matwey** [comment]
Nevermind, I am on a half way to fix it now.
