### ISSUE TITLE
Add support for compressed beam files.

### ISSUE THREAD

**Issue by matwey** [matwey/pybeam#19]

**Comment by lemenkov** [comment]
[test_compressed.erl.txt](https://github.com/matwey/pybeam/files/15365630/test_compressed.erl.txt)

Minimal example (rename to *.erl)

**Comment by matwey** [comment]
```
erlc +compressed test.erl
```

produces a file which can be decompressed via plain `gunzip` tool. And I assume, that `gz` should have its own magic header.
