### ISSUE TITLE
Doesn't work with Erlang 20

### ISSUE THREAD

**Issue by lemenkov** [matwey/pybeam#7]
Erlang 20 introduced a new type of an object - b'AtU8' (UTF-8 encoded atoms). Old b'Atom' type is no longer used.

So import-export tables must be reworked (better with maintaining compatibility with older Erlang versions).

**Comment by lemenkov** [comment]
Example - https://kojipkgs.fedoraproject.org//packages/erlang/20.3/1.fc28/x86_64/erlang-erts-20.3-1.fc28.x86_64.rpm

**Comment by lemenkov** [comment]
https://transfer.sh/pu5vt/erlang.beam.gz

**Comment by matwey** [comment]
Could you please check master now. Is it working for you?

**Comment by lemenkov** [comment]
My tests are passing now. Seems ok.
